### ISSUE TITLE
App crashes after pressing back from album mode

### ISSUE THREAD

**Issue by nesper8** [K1rakishou/KurobaExLite#8]
Exception: java.lang.IllegalStateException
Message: Required value was null.

Stacktrace
```
java.lang.IllegalStateException: Required value was null.
	at androidx.compose.ui.node.DelegatableNodeKt.requireOwner(DelegatableNode.kt:3)
	at androidx.compose.ui.node.NodeKindKt.autoInvalidateNode(NodeKind.kt:17)
	at androidx.compose.ui.node.NodeChain.updateNodeAndReplaceIfNeeded(NodeChain.kt:28)
	at androidx.compose.ui.node.LayoutNode.setModifier(LayoutNode.kt:39)
	at androidx.compose.ui.node.ComposeUiNode$Companion$SetModifier$1.invoke(ComposeUiNode.kt:3)
	at androidx.compose.runtime.ComposerImpl$apply$operation$1.invoke(Composer.kt:3)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:13)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:3)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:44)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:1)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:15)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
	at android.view.Choreographer.doFrame(Choreographer.java:728)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:959)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7700)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@d698135, androidx.compose.ui.platform.MotionDurationScaleImpl@f4859ca, StandaloneCoroutine{Cancelling}@965f73b, AndroidUiDispatcher@4606e58]

```

Logs
```
D/KurobaExLite | MainActivity: onCreate() start isFreshStart: true
D/KurobaExLite | MainActivityIntentHandler: Got intent with action 'android.intent.action.MAIN'
V/KurobaExLite | ApplicationVisibilityManager: onActivityStarted('MainActivity', 165266386)
D/KurobaExLite | ApplicationVisibilityManager: ^^^ App went foreground ^^^
D/KurobaExLite | GlobalUiInfoManager: UiInfoManager initialization started
D/KurobaExLite | GlobalUiInfoManager: UiInfoManager initialization finished
V/KurobaExLite | BaseViewModel: ViewModel MainActivityViewModel created
V/KurobaExLite | NavigationRouter: pushScreen(HomeScreen)
V/KurobaExLite | ComposeScreen: onStartCreating(HomeScreen, AddToNavStack)
D/KurobaExLite | LoadBookmarks: Loaded 0 bookmarks from database
D/KurobaExLite | LoadBookmarks: No active bookmarks loaded, doing nothing
V/KurobaExLite | ApplicationVisibilityManager: onActivityStopped('MainActivity', 165266386)
D/KurobaExLite | ApplicationVisibilityManager: vvv App went background vvv
V/KurobaExLite | DispatchedCoroutine: suspendConvertWithJsonAdapter() url='https://api.github.com/repos/K1rakishou/KurobaExLite/releases' start
V/KurobaExLite | DispatchedCoroutine: suspendConvertWithJsonAdapter() url='https://api.github.com/repos/K1rakishou/KurobaExLite/releases' end
D/KurobaExLite | UpdateManager: latestRelease: Release(tagName=v1.0.10-beta, releaseUrl=https://github.com/K1rakishou/KurobaExLite/releases/tag/v1.0.10-beta, title=v1.0.10-beta, prerelease=true)
V/KurobaExLite | ApplicationVisibilityManager: onActivityStarted('MainActivity', 165266386)
D/KurobaExLite | ApplicationVisibilityManager: ^^^ App went foreground ^^^
V/KurobaExLite | NavigationRouter: pushScreen(CatalogScreen)
V/KurobaExLite | ComposeScreen: onStartCreating(CatalogScreen, AddToNavStack)
V/KurobaExLite | NavigationRouter: pushScreen(ThreadScreen)
V/KurobaExLite | ComposeScreen: onStartCreating(ThreadScreen, AddToNavStack)
V/KurobaExLite | BaseViewModel: ViewModel ReplyLayoutViewModel created
D/KurobaExLite | ReplyLayoutViewModel: processReplyLayoutStates() replyLayoutStateKeys is empty, doing cleanup()
V/KurobaExLite | BaseViewModel: ViewModel CatalogScreenViewModel created
V/KurobaExLite | BaseViewModel: ViewModel ThreadScreenViewModel created
V/KurobaExLite | BaseViewModel: ViewModel HomeScreenViewModel created
D/KurobaExLite | LocalFilePicker: cleanup() removed 0 directories with files
V/KurobaExLite | ComposeScreen: onCreated(HomeScreen, AddToNavStack)
V/KurobaExLite | NavigationRouter: pushScreen(BookmarksScreen)
V/KurobaExLite | ComposeScreen: onStartCreating(BookmarksScreen, AddToNavStack)
V/KurobaExLite | ReplyNotificationsHelper: showOrUpdateNotificationsInternal() currentlyOpenedThread=null, unreadNotificationsGrouped=0
D/KurobaExLite | ReplyNotificationsHelper: showNotificationForReplies(unreadNotificationsGroupedCount=0, currentlyOpenedThread=null)
D/KurobaExLite | ReplyNotificationsHelper: showNotificationForReplies() unreadNotificationsGrouped are empty
D/KurobaExLite | ReplyNotificationsHelper: closeAllNotifications() visibleNotifications are empty
D/KurobaExLite | ThreadScreenViewModel: loadPrevVisitedThread() prevThreadDescriptor is null
D/KurobaExLite | CatalogScreenViewModel: loadPrevVisitedCatalog() prevCatalogDescriptor is null
V/KurobaExLite | BaseViewModel: ViewModel HistoryScreenViewModel created
V/KurobaExLite | BaseViewModel: ViewModel BookmarksScreenViewModel created
V/KurobaExLite | ComposeScreen: onCreated(CatalogScreen, AddToNavStack)
V/KurobaExLite | ComposeScreen: onCreated(ThreadScreen, AddToNavStack)
V/KurobaExLite | ComposeScreen: onCreated(BookmarksScreen, AddToNavStack)
D/KurobaExLite | LoadNavigationHistory: loadFromDatabase(256)
D/KurobaExLite | LoadNavigationHistory: navigationHistoryDao.selectAllOrdered(maxCount) returned empty list
D/KurobaExLite | UpdateManager: versionCodeFromServer (10010) <= lastCheckedVersionCode (10010), currentVersionCode=10010 (already on the latest version)
V/KurobaExLite | ApplicationVisibilityManager: onActivityStopped('MainActivity', 165266386)
D/KurobaExLite | ApplicationVisibilityManager: vvv App went background vvv
D/KurobaExLite | ThreadAutoUpdater: Thread auto-updater paused, currentThreadDescriptor=null
V/KurobaExLite | ApplicationVisibilityManager: onActivityStarted('MainActivity', 165266386)
D/KurobaExLite | ApplicationVisibilityManager: ^^^ App went foreground ^^^
D/KurobaExLite | ThreadAutoUpdater: Thread auto-updater cannot be resumed because currentThreadDescriptor is null
V/KurobaExLite | MainNavigationRouter: presentScreen(FloatingMenuScreen_catalog_overflow_menu) at 0
V/KurobaExLite | ComposeScreen: onStartCreating(FloatingMenuScreen_catalog_overflow_menu, AddToNavStack)
V/KurobaExLite | ComposeScreen: onCreated(FloatingMenuScreen_catalog_overflow_menu, AddToNavStack)
V/KurobaExLite | MainNavigationRouter: stopPresentingScreen(FloatingMenuScreen_catalog_overflow_menu) at 0
V/KurobaExLite | ComposeScreen: onStartDisposing(FloatingMenuScreen_catalog_overflow_menu, RemoveFromNavStack)
V/KurobaExLite | ComposeScreen: onDisposed(FloatingMenuScreen_catalog_overflow_menu, RemoveFromNavStack)
V/KurobaExLite | NavigationRouter: pushScreen(AppSettingsScreen)
V/KurobaExLite | ComposeScreen: onStartCreating(AppSettingsScreen, AddToNavStack)
V/KurobaExLite | BaseViewModel: ViewModel AppSettingsScreenViewModel created
V/KurobaExLite | ComposeScreen: onCreated(AppSettingsScreen, AddToNavStack)
V/KurobaExLite | MainNavigationRouter: presentScreen(FloatingMenuScreen_app_settings_list_option_menu) at 0
V/KurobaExLite | ComposeScreen: onStartCreating(FloatingMenuScreen_app_settings_list_option_menu, AddToNavStack)
V/KurobaExLite | ComposeScreen: onCreated(FloatingMenuScreen_app_settings_list_option_menu, AddToNavStack)
V/KurobaExLite | MainNavigationRouter: stopPresentingScreen(FloatingMenuScreen_app_settings_list_option_menu) at 0
V/KurobaExLite | ComposeScreen: onStartDisposing(FloatingMenuScreen_app_settings_list_option_menu, RemoveFromNavStack)
V/KurobaExLite | ComposeScreen: onDisposed(FloatingMenuScreen_app_settings_list_option_menu, RemoveFromNavStack)
V/KurobaExLite | NavigationRouter: popScreen(AppSettingsScreen)
V/KurobaExLite | ComposeScreen: onStartDisposing(AppSettingsScreen, RemoveFromNavStack)
V/KurobaExLite | ComposeScreen: onDisposed(AppSettingsScreen, RemoveFromNavStack)
V/KurobaExLite | NavigationRouter: pushScreen(CatalogSelectionScreen)
V/KurobaExLite | ComposeScreen: onStartCreating(CatalogSelectionScreen, AddToNavStack)
V/KurobaExLite | BaseViewModel: ViewModel CatalogSelectionScreenViewModel created
V/KurobaExLite | ComposeScreen: onCreated(CatalogSelectionScreen, AddToNavStack)
D/KurobaExLite | GetSiteBoardList: siteKey=4chan, forceReload=false, networkLoadAllowed=true
D/KurobaExLite | GetSiteBoardList: Reading from database...
D/KurobaExLite | GetSiteBoardList: Reading from database... SUCCESS
D/KurobaExLite | GetSiteBoardList: Cached catalogs cannot be used: cachedCatalogsCount: 0
V/KurobaExLite | Chan4DataSource: loadBoards() url='https://a.4cdn.org/boards.json'
V/KurobaExLite | UndispatchedCoroutine: suspendConvertWithJsonAdapter() url='https://a.4cdn.org/boards.json' start
V/KurobaExLite | UndispatchedCoroutine: suspendConvertWithJsonAdapter() url='https://a.4cdn.org/boards.json' end
D/KurobaExLite | GetSiteBoardList: Got boards from network: count=78
D/KurobaExLite | GetSiteBoardList: Inserting 78 siteCatalogs into database...
D/KurobaExLite | GetSiteBoardList: Loaded 0 existing catalog entities from the database
D/KurobaExLite | GetSiteBoardList: insertOrUpdateBoards()
D/KurobaExLite | GetSiteBoardList: insertChanCatalogEntityList() toInsert=78
D/KurobaExLite | GetSiteBoardList: updateChanCatalogEntityList() toUpdate=0
D/KurobaExLite | GetSiteBoardList: insertOrUpdateBoardOrders()
D/KurobaExLite | GetSiteBoardList: insertOrUpdateBoardFlags()
D/KurobaExLite | GetSiteBoardList: Inserting 78 siteCatalogs into database... SUCCESS
V/KurobaExLite | NavigationRouter: pushScreen(SiteSettingsScreen)
V/KurobaExLite | ComposeScreen: onStartCreating(SiteSettingsScreen, AddToNavStack)
V/KurobaExLite | ComposeScreen: onCreated(SiteSettingsScreen, AddToNavStack)
V/KurobaExLite | NavigationRouter: popScreen(SiteSettingsScreen)
V/KurobaExLite | ComposeScreen: onStartDisposing(SiteSettingsScreen, RemoveFromNavStack)
V/KurobaExLite | ComposeScreen: onDisposed(SiteSettingsScreen, RemoveFromNavStack)
V/KurobaExLite | Chan4DataSource: loadCatalog() url='https://a.4cdn.org/g/catalog.json'
V/KurobaExLite | NavigationRouter: popScreen(CatalogSelectionScreen)
V/KurobaExLite | ComposeScreen: onStartDisposing(CatalogSelectionScreen, RemoveFromNavStack)
V/KurobaExLite | UndispatchedCoroutine: suspendConvertWithJsonAdapter() url='https://a.4cdn.org/g/catalog.json' start
D/KurobaExLite | ReplyLayoutState: restoreFromBundle() replyLayoutVisibilityState=Collapsed, attachedImages=''
V/KurobaExLite | UndispatchedCoroutine: suspendConvertWithJsonAdapter() url='https://a.4cdn.org/g/catalog.json' end
V/KurobaExLite | ComposeScreen: onDisposed(CatalogSelectionScreen, RemoveFromNavStack)
D/KurobaExLite | ChanCatalogCache: insert() 151 threads inserted or updated
D/KurobaExLite | DispatchedCoroutine: Parsing posts 16/151, indexes=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], startIndex=0
D/KurobaExLite | PostScreenViewModel: parseRemainingPostsAsync() starting parsing 151 posts, (chunksCount=4, chunkSize=38)
V/KurobaExLite | PostScreenViewModel: parseRemainingPostsAsyncRegular() running chunk 0 with 38 elements on thread post_parser_thread_3
V/KurobaExLite | PostScreenViewModel: parseRemainingPostsAsyncRegular() running chunk 1 with 38 elements on thread post_parser_thread_0
V/KurobaExLite | PostScreenViewModel: parseRemainingPostsAsyncRegular() running chunk 2 with 38 elements on thread post_parser_thread_2
V/KurobaExLite | PostScreenViewModel: parseRemainingPostsAsyncRegular() running chunk 3 with 37 elements on thread post_parser_thread_1
W/KurobaExLite | AbstractSitePostParser: Unsupported tag with name 'pre' found. (postDescriptor=PostDescriptor(4chan/g/91967200/91967200,0), htmlTag=HtmlTag{tagName='pre', attributesCount=1, childrenCount=6, isVoidElement=false})
W/KurobaExLite | AbstractSitePostParser: Unsupported tag with name 'pre' found. (postDescriptor=PostDescriptor(4chan/g/91965058/91965058,0), htmlTag=HtmlTag{tagName='pre', attributesCount=1, childrenCount=12, isVoidElement=false})
V/KurobaExLite | PostScreenViewModel: parseRemainingPostsAsyncRegular() chunk 1 processing finished
W/KurobaExLite | AbstractSitePostParser: Unsupported tag with name 'pre' found. (postDescriptor=PostDescriptor(4chan/g/91961560/91961560,0), htmlTag=HtmlTag{tagName='pre', attributesCount=1, childrenCount=12, isVoidElement=false})
V/KurobaExLite | PostScreenViewModel: parseRemainingPostsAsyncRegular() chunk 0 processing finished
V/KurobaExLite | PostScreenViewModel: parseRemainingPostsAsyncRegular() chunk 2 processing finished
V/KurobaExLite | PostScreenViewModel: parseRemainingPostsAsyncRegular() chunk 3 processing finished
D/KurobaExLite | PostScreenViewModel: parseRemainingPostsAsync() finished parsing 151 posts
D/KurobaExLite | PostScreenViewModel: parseRemainingPostsAsync() sorting 151 posts...
D/KurobaExLite | PostScreenViewModel: parseRemainingPostsAsync() sorting 151 done! Took 5.002539ms
D/KurobaExLite | CatalogScreenViewModel: loadCatalogInternal(CatalogDescriptor(4chan/g)) took 1585 ms, catalogThreads=151
D/KurobaExLite | PostScreenViewModel: restoreScrollPosition(CatalogDescriptor(4chan/g), null) Nothing to restore
D/KurobaExLite | PostScreenViewModel: parseRemainingPostsAsync() parsing 151 posts... done! Took 580 ms
D/KurobaExLite | ParsedPostDataCache: notifyListenersPostDataUpdated() chanDescriptor: CatalogDescriptor(4chan/g), updates: 151
D/KurobaExLite | PersistNavigationHistory: persisted 1 navigation elements
V/KurobaExLite | FastScrollerMarksManager: postDataUpdatesFlow new event chanDescriptor: CatalogDescriptor(4chan/g), postDescriptors: 151
V/KurobaExLite | FastScrollerMarksManager: postDataUpdatesFlow new event chanDescriptor: CatalogDescriptor(4chan/g), postDescriptors: 151, marksList: 0
V/KurobaExLite | MainNavigationRouter: presentScreen(FloatingMenuScreen_catalog_overflow_menu) at 0
V/KurobaExLite | ComposeScreen: onStartCreating(FloatingMenuScreen_catalog_overflow_menu, AddToNavStack)
V/KurobaExLite | ComposeScreen: onCreated(FloatingMenuScreen_catalog_overflow_menu, AddToNavStack)
D/KurobaExLite | CatalogScreenToolbarActionHandler: catalog processClickedToolbarMenuItem id=Album
V/KurobaExLite | NavigationRouter: pushScreen(AlbumScreen)
V/KurobaExLite | ComposeScreen: onStartCreating(AlbumScreen, AddToNavStack)
V/KurobaExLite | MainNavigationRouter: stopPresentingScreen(FloatingMenuScreen_catalog_overflow_menu) at 0
V/KurobaExLite | ComposeScreen: onStartDisposing(FloatingMenuScreen_catalog_overflow_menu, RemoveFromNavStack)
V/KurobaExLite | BaseViewModel: ViewModel AlbumScreenViewModel created
D/KurobaExLite | AlbumScreenViewModel: loadAlbumAndListenForUpdates(CatalogDescriptor(4chan/g))
D/KurobaExLite | AlbumScreenViewModel: loadAlbumAndListenForUpdates() loaded 151 album images
V/KurobaExLite | ComposeScreen: onDisposed(FloatingMenuScreen_catalog_overflow_menu, RemoveFromNavStack)
V/KurobaExLite | ComposeScreen: onCreated(AlbumScreen, AddToNavStack)
V/KurobaExLite | NavigationRouter: popScreen(AlbumScreen)
V/KurobaExLite | ComposeScreen: onStartDisposing(AlbumScreen, RemoveFromNavStack)
V/KurobaExLite | ComposeScreen: onDisposed(AlbumScreen, RemoveFromNavStack)
E/KurobaExLite | KurobaExLiteApplication: Unhandled exception in thread: main, error: java.lang.IllegalStateException: Required value was null.
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.ui.node.DelegatableNodeKt.requireOwner(DelegatableNode.kt:3)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.ui.node.NodeKindKt.autoInvalidateNode(NodeKind.kt:17)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.ui.node.NodeChain.updateNodeAndReplaceIfNeeded(NodeChain.kt:28)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.ui.node.LayoutNode.setModifier(LayoutNode.kt:39)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.ui.node.ComposeUiNode$Companion$SetModifier$1.invoke(ComposeUiNode.kt:3)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.ComposerImpl$apply$operation$1.invoke(Composer.kt:3)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:13)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:3)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:44)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:1)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:15)
E/KurobaExLite | KurobaExLiteApplication: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
E/KurobaExLite | KurobaExLiteApplication: 	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
E/KurobaExLite | KurobaExLiteApplication: 	at android.view.Choreographer.doFrame(Choreographer.java:728)
E/KurobaExLite | KurobaExLiteApplication: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:959)
E/KurobaExLite | KurobaExLiteApplication: 	at android.os.Handler.handleCallback(Handler.java:938)
E/KurobaExLite | KurobaExLiteApplication: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/KurobaExLite | KurobaExLiteApplication: 	at android.os.Looper.loop(Looper.java:223)
E/KurobaExLite | KurobaExLiteApplication: 	at android.app.ActivityThread.main(ActivityThread.java:7700)
E/KurobaExLite | KurobaExLiteApplication: 	at java.lang.reflect.Method.invoke(Native Method)
E/KurobaExLite | KurobaExLiteApplication: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
E/KurobaExLite | KurobaExLiteApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
E/KurobaExLite | KurobaExLiteApplication: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@d698135, androidx.compose.ui.platform.MotionDurationScaleImpl@f4859ca, StandaloneCoroutine{Cancelling}@965f73b, AndroidUiDispatcher@4606e58]
D/KurobaExLite | CrashReportActivity: Got new exception: java.lang.IllegalStateException
V/KurobaExLite | ApplicationVisibilityManager: onActivityStarted('CrashReportActivity', 236982451)
D/KurobaExLite | ApplicationVisibilityManager: ^^^ App went foreground ^^^

```
Additional information
```
Android API Level: 30
App Version: 1.0.10
Phone Model: HMD Global Nokia 2.3
Flavor type: Production
isSlowDevice: false
MemoryClass: 256
App running time: 00:00:21.294
System animations info: duration: 0.5, transition: 0.5, window: 0.5

```

**Comment by K1rakishou** [comment]
Yes, this is a known bug, it's already fixed but the release is blocked by two other crashes in Jetpack Compose.

**Comment by nesper8** [comment]
Thank you I'll close the issue now
